#!/usr/bin/env python

#A simple little script to update all of your Python packages, your Arch packages, as well as pip! Written by Kaede <3

from subprocess import call

print("This tool will attempt to update all of your Python scripts, as well as your Arch system:")

try:
    call("mkdir ~/upkg >/dev/null 2>&1", shell=True)
except Exception:
    pass

call("pip freeze > ~/upkg/requirements.txt", shell=True)
call("sed -i 's/==/>=/g' ~/upkg/requirements.txt", shell=True)

input("Press Enter to continue...\n")

try:
    isPacman = call(['which', 'pacman'])
    if isPacman == 0:
        call("sudo pacman -Syu", shell=True)
    else:
        print("Could not find pacman, continuing to update python packages...")
except Exception:
    pass

call("python -m pip install --upgrade pip", shell=True)
call("pip install -r ~/upkg/requirements.txt --upgrade", shell=True)
print("Done!")
